### ISSUE TITLE
'cat' command print speed

### ISSUE THREAD

**Issue by agarmu** [hackclub/jobs#1]
When I used cat on `game_designer.md`, it printed a small chunk, which was great, but then when it printed the rest of the document, it happened all at once. It would be useful if there was a paging implementation similar to `less` or `more` for longer files, rather than an abrupt print.

**Comment by agarmu** [comment]
This may be worth a look: https://github.com/noborus/ov

**Comment by zachlatta** [comment]
Closed this by implementing a hacky pager before launching last week.
